package io.github.jlrods.mytripsmanager.database

object InitialData {
    fun getCountries(): List<Country> {
        return listOf(
            Country(name = "Afghanistan", currency = "AFN", flag = "af"),
            Country(name = "Albania", currency = "ALL", flag = "al"),
            Country(name = "Algeria", currency = "DZD", flag = "dz"),
            Country(name = "Andorra", currency = "EUR", flag = "ad"),
            Country(name = "Angola", currency = "AOA", flag = "ao"),
            Country(name = "Antigua and Barbuda", currency = "XCD", flag = "ag"),
            Country(name = "Argentina", currency = "ARS", flag = "ar"),
            Country(name = "Armenia", currency = "AMD", flag = "am"),
            Country(name = "Australia", currency = "AUD", flag = "au"),
            Country(name = "Austria", currency = "EUR", flag = "at"),
            Country(name = "Azerbaijan", currency = "AZN", flag = "az"),
            Country(name = "Bahamas", currency = "BSD", flag = "bs"),
            Country(name = "Bahrain", currency = "BHD", flag = "bh"),
            Country(name = "Bangladesh", currency = "BDT", flag = "bd"),
            Country(name = "Barbados", currency = "BBD", flag = "bb"),
            Country(name = "Belarus", currency = "BYN", flag = "by"),
            Country(name = "Belgium", currency = "EUR", flag = "be"),
            Country(name = "Belize", currency = "BZD", flag = "bz"),
            Country(name = "Benin", currency = "XOF", flag = "bj"),
            Country(name = "Bhutan", currency = "BTN", flag = "bt"),
            Country(name = "Bolivia", currency = "BOB", flag = "bo"),
            Country(name = "Bosnia and Herzegovina", currency = "BAM", flag = "ba"),
            Country(name = "Botswana", currency = "BWP", flag = "bw"),
            Country(name = "Brazil", currency = "BRL", flag = "br"),
            Country(name = "Brunei", currency = "BND", flag = "bn"),
            Country(name = "Bulgaria", currency = "BGN", flag = "bg"),
            Country(name = "Burkina Faso", currency = "XOF", flag = "bf"),
            Country(name = "Burundi", currency = "BIF", flag = "bi"),
            Country(name = "Cabo Verde", currency = "CVE", flag = "cv"),
            Country(name = "Cambodia", currency = "KHR", flag = "kh"),
            Country(name = "Cameroon", currency = "XAF", flag = "cm"),
            Country(name = "Canada", currency = "CAD", flag = "ca"),
            Country(name = "Central African Republic", currency = "XAF", flag = "cf"),
            Country(name = "Chad", currency = "XAF", flag = "td"),
            Country(name = "Chile", currency = "CLP", flag = "cl"),
            Country(name = "China", currency = "CNY", flag = "cn"),
            Country(name = "Colombia", currency = "COP", flag = "co"),
            Country(name = "Comoros", currency = "KMF", flag = "km"),
            Country(name = "Congo, Democratic Republic of the", currency = "CDF", flag = "cd"),
            Country(name = "Congo, Republic of the", currency = "XAF", flag = "cg"),
            Country(name = "Costa Rica", currency = "CRC", flag = "cr"),
            Country(name = "Cote d'Ivoire", currency = "XOF", flag = "ci"),
            Country(name = "Croatia", currency = "EUR", flag = "hr"),
            Country(name = "Cuba", currency = "CUP", flag = "cu"),
            Country(name = "Cyprus", currency = "EUR", flag = "cy"),
            Country(name = "Czechia", currency = "CZK", flag = "cz"),
            Country(name = "Denmark", currency = "DKK", flag = "dk"),
            Country(name = "Djibouti", currency = "DJF", flag = "dj"),
            Country(name = "Dominica", currency = "XCD", flag = "dm"),
            Country(name = "Dominican Republic", currency = "DOP", flag = "dom"),
            Country(name = "Ecuador", currency = "USD", flag = "ec"),
            Country(name = "Egypt", currency = "EGP", flag = "eg"),
            Country(name = "El Salvador", currency = "USD", flag = "sv"),
            Country(name = "Equatorial Guinea", currency = "XAF", flag = "gq"),
            Country(name = "Eritrea", currency = "ERN", flag = "er"),
            Country(name = "Estonia", currency = "EUR", flag = "ee"),
            Country(name = "Eswatini", currency = "SZL", flag = "sz"),
            Country(name = "Ethiopia", currency = "ETB", flag = "et"),
            Country(name = "Fiji", currency = "FJD", flag = "fj"),
            Country(name = "Finland", currency = "EUR", flag = "fi"),
            Country(name = "France", currency = "EUR", flag = "fr"),
            Country(name = "Gabon", currency = "XAF", flag = "ga"),
            Country(name = "Gambia", currency = "GMD", flag = "gm"),
            Country(name = "Georgia", currency = "GEL", flag = "ge"),
            Country(name = "Germany", currency = "EUR", flag = "de"),
            Country(name = "Ghana", currency = "GHS", flag = "gh"),
            Country(name = "Greece", currency = "EUR", flag = "gr"),
            Country(name = "Grenada", currency = "XCD", flag = "gd"),
            Country(name = "Guatemala", currency = "GTQ", flag = "gt"),
            Country(name = "Guinea", currency = "GNF", flag = "gn"),
            Country(name = "Guinea-Bissau", currency = "XOF", flag = "gw"),
            Country(name = "Guyana", currency = "GYD", flag = "gy"),
            Country(name = "Haiti", currency = "HTG", flag = "ht"),
            Country(name = "Honduras", currency = "HNL", flag = "hn"),
            Country(name = "Hungary", currency = "HUF", flag = "hu"),
            Country(name = "Iceland", currency = "ISK", flag = "is"),
            Country(name = "India", currency = "INR", flag = "in"),
            Country(name = "Indonesia", currency = "IDR", flag = "id"),
            Country(name = "Iran", currency = "IRR", flag = "ir"),
            Country(name = "Iraq", currency = "IQD", flag = "iq"),
            Country(name = "Ireland", currency = "EUR", flag = "ie"),
            Country(name = "Israel", currency = "ILS", flag = "il"),
            Country(name = "Italy", currency = "EUR", flag = "it"),
            Country(name = "Jamaica", currency = "JMD", flag = "jm"),
            Country(name = "Japan", currency = "JPY", flag = "jp"),
            Country(name = "Jordan", currency = "JOD", flag = "jo"),
            Country(name = "Kazakhstan", currency = "KZT", flag = "kz"),
            Country(name = "Kenya", currency = "KES", flag = "ke"),
            Country(name = "Kiribati", currency = "AUD", flag = "ki"),
            Country(name = "Kuwait", currency = "KWD", flag = "kw"),
            Country(name = "Kyrgyzstan", currency = "KGS", flag = "kg"),
            Country(name = "Laos", currency = "LAK", flag = "la"),
            Country(name = "Latvia", currency = "EUR", flag = "lv"),
            Country(name = "Lebanon", currency = "LBP", flag = "lb"),
            Country(name = "Lesotho", currency = "LSL", flag = "ls"),
            Country(name = "Liberia", currency = "LRD", flag = "lr"),
            Country(name = "Libya", currency = "LYD", flag = "ly"),
            Country(name = "Liechtenstein", currency = "CHF", flag = "li"),
            Country(name = "Lithuania", currency = "EUR", flag = "lt"),
            Country(name = "Luxembourg", currency = "EUR", flag = "lu"),
            Country(name = "Madagascar", currency = "MGA", flag = "mg"),
            Country(name = "Malawi", currency = "MWK", flag = "mw"),
            Country(name = "Malaysia", currency = "MYR", flag = "my"),
            Country(name = "Maldives", currency = "MVR", flag = "mv"),
            Country(name = "Mali", currency = "XOF", flag = "ml"),
            Country(name = "Malta", currency = "EUR", flag = "mt"),
            Country(name = "Marshall Islands", currency = "USD", flag = "mh"),
            Country(name = "Mauritania", currency = "MRU", flag = "mr"),
            Country(name = "Mauritius", currency = "MUR", flag = "mu"),
            Country(name = "Mexico", currency = "MXN", flag = "mx"),
            Country(name = "Micronesia", currency = "USD", flag = "fm"),
            Country(name = "Moldova", currency = "MDL", flag = "md"),
            Country(name = "Monaco", currency = "EUR", flag = "mc"),
            Country(name = "Mongolia", currency = "MNT", flag = "mn"),
            Country(name = "Montenegro", currency = "EUR", flag = "me"),
            Country(name = "Morocco", currency = "MAD", flag = "ma"),
            Country(name = "Mozambique", currency = "MZN", flag = "mz"),
            Country(name = "Myanmar", currency = "MMK", flag = "mm"),
            Country(name = "Namibia", currency = "NAD", flag = "na"),
            Country(name = "Nauru", currency = "AUD", flag = "nr"),
            Country(name = "Nepal", currency = "NPR", flag = "np"),
            Country(name = "Netherlands", currency = "EUR", flag = "nl"),
            Country(name = "New Zealand", currency = "NZD", flag = "nz"),
            Country(name = "Nicaragua", currency = "NIO", flag = "ni"),
            Country(name = "Niger", currency = "XOF", flag = "ne"),
            Country(name = "Nigeria", currency = "NGN", flag = "ng"),
            Country(name = "North Korea", currency = "KPW", flag = "kp"),
            Country(name = "North Macedonia", currency = "MKD", flag = "mk"),
            Country(name = "Norway", currency = "NOK", flag = "no"),
            Country(name = "Oman", currency = "OMR", flag = "om"),
            Country(name = "Pakistan", currency = "PKR", flag = "pk"),
            Country(name = "Palau", currency = "USD", flag = "pw"),
            Country(name = "Panama", currency = "PAB", flag = "pa"),
            Country(name = "Papua New Guinea", currency = "PGK", flag = "pg"),
            Country(name = "Paraguay", currency = "PYG", flag = "py"),
            Country(name = "Peru", currency = "PEN", flag = "pe"),
            Country(name = "Philippines", currency = "PHP", flag = "ph"),
            Country(name = "Poland", currency = "PLN", flag = "pl"),
            Country(name = "Portugal", currency = "EUR", flag = "pt"),
            Country(name = "Qatar", currency = "QAR", flag = "qa"),
            Country(name = "Romania", currency = "RON", flag = "ro"),
            Country(name = "Russia", currency = "RUB", flag = "ru"),
            Country(name = "Rwanda", currency = "RWF", flag = "rw"),
            Country(name = "Saint Kitts and Nevis", currency = "XCD", flag = "kn"),
            Country(name = "Saint Lucia", currency = "XCD", flag = "lc"),
            Country(name = "Saint Vincent and the Grenadines", currency = "XCD", flag = "vc"),
            Country(name = "Samoa", currency = "WST", flag = "ws"),
            Country(name = "San Marino", currency = "EUR", flag = "sm"),
            Country(name = "Sao Tome and Principe", currency = "STN", flag = "st"),
            Country(name = "Saudi Arabia", currency = "SAR", flag = "sa"),
            Country(name = "Senegal", currency = "XOF", flag = "sn"),
            Country(name = "Serbia", currency = "RSD", flag = "rs"),
            Country(name = "Seychelles", currency = "SCR", flag = "sc"),
            Country(name = "Sierra Leone", currency = "SLL", flag = "sl"),
            Country(name = "Singapore", currency = "SGD", flag = "sg"),
            Country(name = "Slovakia", currency = "EUR", flag = "sk"),
            Country(name = "Slovenia", currency = "EUR", flag = "si"),
            Country(name = "Solomon Islands", currency = "SBD", flag = "sb"),
            Country(name = "Somalia", currency = "SOS", flag = "so"),
            Country(name = "South Africa", currency = "ZAR", flag = "za"),
            Country(name = "South Korea", currency = "KRW", flag = "kr"),
            Country(name = "South Sudan", currency = "SSP", flag = "ss"),
            Country(name = "Spain", currency = "EUR", flag = "es"),
            Country(name = "Sri Lanka", currency = "LKR", flag = "lk"),
            Country(name = "Sudan", currency = "SDG", flag = "sd"),
            Country(name = "Suriname", currency = "SRD", flag = "sr"),
            Country(name = "Sweden", currency = "SEK", flag = "se"),
            Country(name = "Switzerland", currency = "CHF", flag = "ch"),
            Country(name = "Syria", currency = "SYP", flag = "sy"),
            Country(name = "Taiwan", currency = "TWD", flag = "tw"),
            Country(name = "Tajikistan", currency = "TJS", flag = "tj"),
            Country(name = "Tanzania", currency = "TZS", flag = "tz"),
            Country(name = "Thailand", currency = "THB", flag = "th"),
            Country(name = "Timor-Leste", currency = "USD", flag = "tl"),
            Country(name = "Togo", currency = "XOF", flag = "tg"),
            Country(name = "Tonga", currency = "TOP", flag = "to"),
            Country(name = "Trinidad and Tobago", currency = "TTD", flag = "tt"),
            Country(name = "Tunisia", currency = "TND", flag = "tn"),
            Country(name = "Turkey", currency = "TRY", flag = "tr"),
            Country(name = "Turkmenistan", currency = "TMT", flag = "tm"),
            Country(name = "Tuvalu", currency = "AUD", flag = "tv"),
            Country(name = "Uganda", currency = "UGX", flag = "ug"),
            Country(name = "Ukraine", currency = "UAH", flag = "ua"),
            Country(name = "United Arab Emirates", currency = "AED", flag = "ae"),
            Country(name = "United Kingdom", currency = "GBP", flag = "gb"),
            Country(name = "United States of America", currency = "USD", flag = "us"),
            Country(name = "Uruguay", currency = "UYU", flag = "uy"),
            Country(name = "Uzbekistan", currency = "UZS", flag = "uz"),
            Country(name = "Vanuatu", currency = "VUV", flag = "vu"),
            Country(name = "Vatican City", currency = "EUR", flag = "va"),
            Country(name = "Venezuela", currency = "VES", flag = "ve"),
            Country(name = "Vietnam", currency = "VND", flag = "vn"),
            Country(name = "Yemen", currency = "YER", flag = "ye"),
            Country(name = "Zambia", currency = "ZMW", flag = "zm"),
            Country(name = "Zimbabwe", currency = "ZWL", flag = "zw")
        )
    }

    fun getExpenseTypes(): List<ExpenseType> {
        return listOf(
            ExpenseType(name = "Accommodation", logo = "ic_accommodation"),
            ExpenseType(name = "Airline Tickets", logo = "ic_airline_tickets"),
            ExpenseType(name = "Food", logo = "ic_food"),
            ExpenseType(name = "Transport", logo = "ic_transport"),
            ExpenseType(name = "Leisure", logo = "ic_leisure"),
            ExpenseType(name = "Insurance", logo = "ic_insurance"),
            ExpenseType(name = "Health", logo = "ic_health"),
            ExpenseType(name = "Parking", logo = "ic_parking"),
            ExpenseType(name = "Drinks", logo = "ic_drinks"),
            ExpenseType(name = "Others", logo = "ic_others"),
            ExpenseType(name = "Souvenirs", logo = "ic_souvenirs")
        )
    }
}