package io.github.jlrods.mytripsmanager.database

import android.util.Log
import io.github.jlrods.mytripsmanager.R

object InitialData {

    fun getCountries(): List<Country> {
        return listOf(
            Country(name = "afghanistan", currency = "AFN", flagRes = R.drawable.af),
            Country(name = "albania", currency = "ALL", flagRes = R.drawable.al),
            Country(name = "algeria", currency = "DZD", flagRes = R.drawable.dz),
            Country(name = "andorra", currency = "EUR", flagRes = R.drawable.ad),
            Country(name = "angola", currency = "AOA", flagRes = R.drawable.ao),
            Country(name = "antigua and barbuda", currency = "XCD", flagRes = R.drawable.ag),
            Country(name = "argentina", currency = "ARS", flagRes = R.drawable.ar),
            Country(name = "armenia", currency = "AMD", flagRes = R.drawable.am),
            Country(name = "australia", currency = "AUD", flagRes = R.drawable.au),
            Country(name = "austria", currency = "EUR", flagRes = R.drawable.at),
            Country(name = "azerbaijan", currency = "AZN", flagRes = R.drawable.az),
            Country(name = "bahamas", currency = "BSD", flagRes = R.drawable.bs),
            Country(name = "bahrain", currency = "BHD", flagRes = R.drawable.bh),
            Country(name = "bangladesh", currency = "BDT", flagRes = R.drawable.bd),
            Country(name = "barbados", currency = "BBD", flagRes = R.drawable.bb),
            Country(name = "belarus", currency = "BYN", flagRes = R.drawable.by),
            Country(name = "belgium", currency = "EUR", flagRes = R.drawable.be),
            Country(name = "belize", currency = "BZD", flagRes = R.drawable.bz),
            Country(name = "benin", currency = "XOF", flagRes = R.drawable.bj),
            Country(name = "bhutan", currency = "BTN", flagRes = R.drawable.bt),
            Country(name = "bolivia", currency = "BOB", flagRes = R.drawable.bo),
            Country(name = "bosnia and herzegovina", currency = "BAM", flagRes = R.drawable.ba),
            Country(name = "botswana", currency = "BWP", flagRes = R.drawable.bw),
            Country(name = "brazil", currency = "BRL", flagRes = R.drawable.br),
            Country(name = "brunei", currency = "BND", flagRes = R.drawable.bn),
            Country(name = "bulgaria", currency = "BGN", flagRes = R.drawable.bg),
            Country(name = "burkina faso", currency = "XOF", flagRes = R.drawable.bf),
            Country(name = "burundi", currency = "BIF", flagRes = R.drawable.bi),
            Country(name = "cabo verde", currency = "CVE", flagRes = R.drawable.cv),
            Country(name = "cambodia", currency = "KHR", flagRes = R.drawable.kh),
            Country(name = "cameroon", currency = "XAF", flagRes = R.drawable.cm),
            Country(name = "canada", currency = "CAD", flagRes = R.drawable.ca),
            Country(name = "central african republic", currency = "XAF", flagRes = R.drawable.cf),
            Country(name = "chad", currency = "XAF", flagRes = R.drawable.td),
            Country(name = "chile", currency = "CLP", flagRes = R.drawable.cl),
            Country(name = "china", currency = "CNY", flagRes = R.drawable.cn),
            Country(name = "colombia", currency = "COP", flagRes = R.drawable.co),
            Country(name = "comoros", currency = "KMF", flagRes = R.drawable.km),
            Country(name = "congo, democratic republic of the", currency = "CDF", flagRes = R.drawable.cd),
            Country(name = "congo, republic of the", currency = "XAF", flagRes = R.drawable.cg),
            Country(name = "costa rica", currency = "CRC", flagRes = R.drawable.cr),
            Country(name = "cote d'ivoire", currency = "XOF", flagRes = R.drawable.ci),
            Country(name = "croatia", currency = "EUR", flagRes = R.drawable.hr),
            Country(name = "cuba", currency = "CUP", flagRes = R.drawable.cu),
            Country(name = "cyprus", currency = "EUR", flagRes = R.drawable.cy),
            Country(name = "czechia", currency = "CZK", flagRes = R.drawable.cz),
            Country(name = "denmark", currency = "DKK", flagRes = R.drawable.dk),
            Country(name = "djibouti", currency = "DJF", flagRes = R.drawable.dj),
            Country(name = "dominica", currency = "XCD", flagRes = R.drawable.dm),
            Country(name = "dominican republic", currency = "DOP", flagRes = R.drawable.dom),
            Country(name = "ecuador", currency = "USD", flagRes = R.drawable.ec),
            Country(name = "egypt", currency = "EGP", flagRes = R.drawable.eg),
            Country(name = "el salvador", currency = "USD", flagRes = R.drawable.sv),
            Country(name = "equatorial guinea", currency = "XAF", flagRes = R.drawable.gq),
            Country(name = "eritrea", currency = "ERN", flagRes = R.drawable.er),
            Country(name = "estonia", currency = "EUR", flagRes = R.drawable.ee),
            Country(name = "eswatini", currency = "SZL", flagRes = R.drawable.sz),
            Country(name = "ethiopia", currency = "ETB", flagRes = R.drawable.et),
            Country(name = "fiji", currency = "FJD", flagRes = R.drawable.fj),
            Country(name = "finland", currency = "EUR", flagRes = R.drawable.fi),
            Country(name = "france", currency = "EUR", flagRes = R.drawable.fr),
            Country(name = "gabon", currency = "XAF", flagRes = R.drawable.ga),
            Country(name = "gambia", currency = "GMD", flagRes = R.drawable.gm),
            Country(name = "georgia", currency = "GEL", flagRes = R.drawable.ge),
            Country(name = "germany", currency = "EUR", flagRes = R.drawable.de),
            Country(name = "ghana", currency = "GHS", flagRes = R.drawable.gh),
            Country(name = "greece", currency = "EUR", flagRes = R.drawable.gr),
            Country(name = "grenada", currency = "XCD", flagRes = R.drawable.gd),
            Country(name = "guatemala", currency = "GTQ", flagRes = R.drawable.gt),
            Country(name = "guinea", currency = "GNF", flagRes = R.drawable.gn),
            Country(name = "guinea-bissau", currency = "XOF", flagRes = R.drawable.gw),
            Country(name = "guyana", currency = "GYD", flagRes = R.drawable.gy),
            Country(name = "haiti", currency = "HTG", flagRes = R.drawable.ht),
            Country(name = "honduras", currency = "HNL", flagRes = R.drawable.hn),
            Country(name = "hungary", currency = "HUF", flagRes = R.drawable.hu),
            Country(name = "iceland", currency = "ISK", flagRes = R.drawable.`is`),
            Country(name = "india", currency = "INR", flagRes = R.drawable.`in`),
            Country(name = "indonesia", currency = "IDR", flagRes = R.drawable.id),
            Country(name = "iran", currency = "IRR", flagRes = R.drawable.ir),
            Country(name = "iraq", currency = "IQD", flagRes = R.drawable.iq),
            Country(name = "ireland", currency = "EUR", flagRes = R.drawable.ie),
            Country(name = "israel", currency = "ILS", flagRes = R.drawable.il),
            Country(name = "italy", currency = "EUR", flagRes = R.drawable.it),
            Country(name = "jamaica", currency = "JMD", flagRes = R.drawable.jm),
            Country(name = "japan", currency = "JPY", flagRes = R.drawable.jp),
            Country(name = "jordan", currency = "JOD", flagRes = R.drawable.jo),
            Country(name = "kazakhstan", currency = "KZT", flagRes = R.drawable.kz),
            Country(name = "kenya", currency = "KES", flagRes = R.drawable.ke),
            Country(name = "kiribati", currency = "AUD", flagRes = R.drawable.ki),
            Country(name = "kuwait", currency = "KWD", flagRes = R.drawable.kw),
            Country(name = "kyrgyzstan", currency = "KGS", flagRes = R.drawable.kg),
            Country(name = "laos", currency = "LAK", flagRes = R.drawable.la),
            Country(name = "latvia", currency = "EUR", flagRes = R.drawable.lv),
            Country(name = "lebanon", currency = "LBP", flagRes = R.drawable.lb),
            Country(name = "lesotho", currency = "LSL", flagRes = R.drawable.ls),
            Country(name = "liberia", currency = "LRD", flagRes = R.drawable.lr),
            Country(name = "libya", currency = "LYD", flagRes = R.drawable.ly),
            Country(name = "liechtenstein", currency = "CHF", flagRes = R.drawable.li),
            Country(name = "lithuania", currency = "EUR", flagRes = R.drawable.lt),
            Country(name = "luxembourg", currency = "EUR", flagRes = R.drawable.lu),
            Country(name = "madagascar", currency = "MGA", flagRes = R.drawable.mg),
            Country(name = "malawi", currency = "MWK", flagRes = R.drawable.mw),
            Country(name = "malaysia", currency = "MYR", flagRes = R.drawable.my),
            Country(name = "maldives", currency = "MVR", flagRes = R.drawable.mv),
            Country(name = "mali", currency = "XOF", flagRes = R.drawable.ml),
            Country(name = "malta", currency = "EUR", flagRes = R.drawable.mt),
            Country(name = "marshall islands", currency = "USD", flagRes = R.drawable.mh),
            Country(name = "mauritania", currency = "MRU", flagRes = R.drawable.mr),
            Country(name = "mauritius", currency = "MUR", flagRes = R.drawable.mu),
            Country(name = "mexico", currency = "MXN", flagRes = R.drawable.mx),
            Country(name = "micronesia", currency = "USD", flagRes = R.drawable.fm),
            Country(name = "moldova", currency = "MDL", flagRes = R.drawable.md),
            Country(name = "monaco", currency = "EUR", flagRes = R.drawable.mc),
            Country(name = "mongolia", currency = "MNT", flagRes = R.drawable.mn),
            Country(name = "montenegro", currency = "EUR", flagRes = R.drawable.me),
            Country(name = "morocco", currency = "MAD", flagRes = R.drawable.ma),
            Country(name = "mozambique", currency = "MZN", flagRes = R.drawable.mz),
            Country(name = "myanmar", currency = "MMK", flagRes = R.drawable.mm),
            Country(name = "namibia", currency = "NAD", flagRes = R.drawable.na),
            Country(name = "nauru", currency = "AUD", flagRes = R.drawable.nr),
            Country(name = "nepal", currency = "NPR", flagRes = R.drawable.np),
            Country(name = "netherlands", currency = "EUR", flagRes = R.drawable.nl),
            Country(name = "new zealand", currency = "NZD", flagRes = R.drawable.nz),
            Country(name = "nicaragua", currency = "NIO", flagRes = R.drawable.ni),
            Country(name = "niger", currency = "XOF", flagRes = R.drawable.ne),
            Country(name = "nigeria", currency = "NGN", flagRes = R.drawable.ng),
            Country(name = "north korea", currency = "KPW", flagRes = R.drawable.kp),
            Country(name = "north macedonia", currency = "MKD", flagRes = R.drawable.mk),
            Country(name = "norway", currency = "NOK", flagRes = R.drawable.no),
            Country(name = "oman", currency = "OMR", flagRes = R.drawable.om),
            Country(name = "pakistan", currency = "PKR", flagRes = R.drawable.pk),
            Country(name = "palau", currency = "USD", flagRes = R.drawable.pw),
            Country(name = "panama", currency = "PAB", flagRes = R.drawable.pa),
            Country(name = "papua new guinea", currency = "PGK", flagRes = R.drawable.pg),
            Country(name = "paraguay", currency = "PYG", flagRes = R.drawable.py),
            Country(name = "peru", currency = "PEN", flagRes = R.drawable.pe),
            Country(name = "philippines", currency = "PHP", flagRes = R.drawable.ph),
            Country(name = "poland", currency = "PLN", flagRes = R.drawable.pl),
            Country(name = "portugal", currency = "EUR", flagRes = R.drawable.pt),
            Country(name = "qatar", currency = "QAR", flagRes = R.drawable.qa),
            Country(name = "romania", currency = "RON", flagRes = R.drawable.ro),
            Country(name = "russia", currency = "RUB", flagRes = R.drawable.ru),
            Country(name = "rwanda", currency = "RWF", flagRes = R.drawable.rw),
            Country(name = "saint kitts and nevis", currency = "XCD", flagRes = R.drawable.kn),
            Country(name = "saint lucia", currency = "XCD", flagRes = R.drawable.lc),
            Country(name = "saint vincent and the grenadines", currency = "XCD", flagRes = R.drawable.vc),
            Country(name = "samoa", currency = "WST", flagRes = R.drawable.ws),
            Country(name = "san marino", currency = "EUR", flagRes = R.drawable.sm),
            Country(name = "sao tome and principe", currency = "STN", flagRes = R.drawable.st),
            Country(name = "saudi arabia", currency = "SAR", flagRes = R.drawable.sa),
            Country(name = "senegal", currency = "XOF", flagRes = R.drawable.sn),
            Country(name = "serbia", currency = "RSD", flagRes = R.drawable.rs),
            Country(name = "seychelles", currency = "SCR", flagRes = R.drawable.sc),
            Country(name = "sierra leone", currency = "SLL", flagRes = R.drawable.sl),
            Country(name = "singapore", currency = "SGD", flagRes = R.drawable.sg),
            Country(name = "slovakia", currency = "EUR", flagRes = R.drawable.sk),
            Country(name = "slovenia", currency = "EUR", flagRes = R.drawable.si),
            Country(name = "solomon islands", currency = "SBD", flagRes = R.drawable.sb),
            Country(name = "somalia", currency = "SOS", flagRes = R.drawable.so),
            Country(name = "south africa", currency = "ZAR", flagRes = R.drawable.za),
            Country(name = "south korea", currency = "KRW", flagRes = R.drawable.kr),
            Country(name = "south sudan", currency = "SSP", flagRes = R.drawable.ss),
            Country(name = "spain", currency = "EUR", flagRes = R.drawable.es),
            Country(name = "sri lanka", currency = "LKR", flagRes = R.drawable.lk),
            Country(name = "sudan", currency = "SDG", flagRes = R.drawable.sd),
            Country(name = "suriname", currency = "SRD", flagRes = R.drawable.sr),
            Country(name = "sweden", currency = "SEK", flagRes = R.drawable.se),
            Country(name = "switzerland", currency = "CHF", flagRes = R.drawable.ch),
            Country(name = "syria", currency = "SYP", flagRes = R.drawable.sy),
            Country(name = "taiwan", currency = "TWD", flagRes = R.drawable.tw),
            Country(name = "tajikistan", currency = "TJS", flagRes = R.drawable.tj),
            Country(name = "tanzania", currency = "TZS", flagRes = R.drawable.tz),
            Country(name = "thailand", currency = "THB", flagRes = R.drawable.th),
            Country(name = "timor-leste", currency = "USD", flagRes = R.drawable.tl),
            Country(name = "togo", currency = "XOF", flagRes = R.drawable.tg),
            Country(name = "tonga", currency = "TOP", flagRes = R.drawable.to),
            Country(name = "trinidad and tobago", currency = "TTD", flagRes = R.drawable.tt),
            Country(name = "tunisia", currency = "TND", flagRes = R.drawable.tn),
            Country(name = "turkey", currency = "TRY", flagRes = R.drawable.tr),
            Country(name = "turkmenistan", currency = "TMT", flagRes = R.drawable.tm),
            Country(name = "tuvalu", currency = "AUD", flagRes = R.drawable.tv),
            Country(name = "uganda", currency = "UGX", flagRes = R.drawable.ug),
            Country(name = "ukraine", currency = "UAH", flagRes = R.drawable.ua),
            Country(name = "united arab emirates", currency = "AED", flagRes = R.drawable.ae),
            Country(name = "united kingdom", currency = "GBP", flagRes = R.drawable.gb),
            Country(name = "united states of america", currency = "USD", flagRes = R.drawable.us),
            Country(name = "uruguay", currency = "UYU", flagRes = R.drawable.uy),
            Country(name = "uzbekistan", currency = "UZS", flagRes = R.drawable.uz),
            Country(name = "vanuatu", currency = "VUV", flagRes = R.drawable.vu),
            Country(name = "vatican city", currency = "EUR", flagRes = R.drawable.va),
            Country(name = "venezuela", currency = "VES", flagRes = R.drawable.ve),
            Country(name = "vietnam", currency = "VND", flagRes = R.drawable.vn),
            Country(name = "yemen", currency = "YER", flagRes = R.drawable.ye),
            Country(name = "zambia", currency = "ZMW", flagRes = R.drawable.zm),
            Country(name = "zimbabwe", currency = "ZWL", flagRes = R.drawable.zw)
        )
    }

    fun getEuropeanCities(countryIdMap: Map<String, Int>): List<City> {
        return listOf(
            City(name = "paris", countryId = countryIdMap["france"]!!),
            City(name = "rome", countryId = countryIdMap["italy"]!!),
            City(name = "madrid", countryId = countryIdMap["spain"]!!),
            City(name = "barcelona", countryId = countryIdMap["spain"]!!),
            City(name = "berlin", countryId = countryIdMap["germany"]!!),
            City(name = "munich", countryId = countryIdMap["germany"]!!),
            City(name = "amsterdam", countryId = countryIdMap["netherlands"]!!),
            City(name = "brussels", countryId = countryIdMap["belgium"]!!),
            City(name = "vienna", countryId = countryIdMap["austria"]!!),
            City(name = "prague", countryId = countryIdMap["czechia"]!!),
            City(name = "budapest", countryId = countryIdMap["hungary"]!!),
            City(name = "lisbon", countryId = countryIdMap["portugal"]!!),
            City(name = "athens", countryId = countryIdMap["greece"]!!),
            City(name = "copenhagen", countryId = countryIdMap["denmark"]!!),
            City(name = "stockholm", countryId = countryIdMap["sweden"]!!),
            City(name = "oslo", countryId = countryIdMap["norway"]!!),
            City(name = "helsinki", countryId = countryIdMap["finland"]!!),
            City(name = "dublin", countryId = countryIdMap["ireland"]!!),
            City(name = "zurich", countryId = countryIdMap["switzerland"]!!),
            City(name = "venice", countryId = countryIdMap["italy"]!!)
        )
    }


    fun getExpenseTypes(): List<ExpenseType> {
        return listOf(
            ExpenseType(name = "Accommodation", iconRes = R.drawable.ic_accommodation),
            ExpenseType(name = "Airline Tickets", iconRes = R.drawable.ic_airline_tickets),
            ExpenseType(name = "Food", iconRes = R.drawable.ic_food),
            ExpenseType(name = "Transport", iconRes = R.drawable.ic_transport),
            ExpenseType(name = "Leisure", iconRes = R.drawable.ic_leisure),
            ExpenseType(name = "Insurance", iconRes = R.drawable.ic_insurance),
            ExpenseType(name = "Health", iconRes = R.drawable.ic_health),
            ExpenseType(name = "Parking", iconRes = R.drawable.ic_parking),
            ExpenseType(name = "Drinks", iconRes = R.drawable.ic_drinks),
            ExpenseType(name = "Others", iconRes = R.drawable.ic_others),
            ExpenseType(name = "Souvenirs", iconRes = R.drawable.ic_souvenirs),
            ExpenseType(name = "Tolls", iconRes = R.drawable.ic_tolls)
        )
    }

    fun getProviders(): List<Provider> {
        return listOf(
            Provider(name = "ryanair", logoRes = R.drawable.logo_ryanair),
            Provider(name = "lufthansa", logoRes = R.drawable.logo_lufthansa),
            Provider(name = "kml", logoRes = R.drawable.logo_kml),
            Provider(name = "air france", logoRes = R.drawable.logo_airfrance),
            Provider(name = "british airways", logoRes = R.drawable.logo_britishairways),
            Provider(name = "iberia", logoRes = R.drawable.logo_iberia),
            Provider(name = "aer lingus", logoRes = R.drawable.logo_aerlingus),
            Provider(name = "easyjet", logoRes = R.drawable.logo_easyjet),
            Provider(name = "turkish airlines", logoRes = R.drawable.logo_turkishairlines),
            Provider(name = "norwegian", logoRes = R.drawable.logo_norwegian),
            Provider(name = "aireuropa", logoRes = R.drawable.logo_aireuropa),
            Provider(name = "conviasa", logoRes = R.drawable.logo_conviasa),
            Provider(name = "copa airlines", logoRes = R.drawable.logo_copaairlines),
            Provider(name = "american airlines", logoRes = R.drawable.logo_americanairlines),
            Provider(name = "booking.com", logoRes = R.drawable.logo_booking),
            Provider(name = "loveholidays.com", logoRes = R.drawable.logo_loveholidays),
            Provider(name = "hertz", logoRes = R.drawable.logo_hertz),
            Provider(name = "avis", logoRes = R.drawable.logo_avis),
            Provider(name = "europcar", logoRes = R.drawable.logo_europcar),
            Provider(name = "sixt", logoRes = R.drawable.logo_sixt),
            Provider(name = "enterprise", logoRes = R.drawable.logo_enterprise),
            Provider(name = "goldcar", logoRes = R.drawable.logo_goldcar),
            Provider(name = "dublin airport", logoRes = R.drawable.logo_dublinairport),
            Provider(name = "shannon airport", logoRes = R.drawable.logo_shannonairport),
            Provider(name = "cork airport", logoRes = R.drawable.logo_corkairport),
            Provider(name = "bus eireann", logoRes = R.drawable.logo_buseirean),
            Provider(name = "go-ahead ireland", logoRes = R.drawable.logo_goaheadireland),
            Provider(name = "dublin bus", logoRes = R.drawable.logo_dublinbus),
            Provider(name = "vhi healthcare", logoRes = R.drawable.logo_vhi),
            Provider(name = "laya healthcare", logoRes = R.drawable.logo_laya),
            Provider(name = "irish life health", logoRes = R.drawable.logo_irishlife),
            Provider(name = "aviva", logoRes = R.drawable.logo_aviva),
            Provider(name = "axa", logoRes = R.drawable.logo_axa)
        )
    }

}