package io.github.jlrods.mytripsmanager.database

import io.github.jlrods.mytripsmanager.R

object InitialData {
    fun getCountries(): List<Country> {
        return listOf(
            Country(name = "Afghanistan", currency = "AFN", flagRes = R.drawable.afganistan),
            Country(name = "Albania", currency = "ALL", flagRes = R.drawable.al),
            Country(name = "Algeria", currency = "DZD", flagRes = R.drawable.dz),
            Country(name = "Andorra", currency = "EUR", flagRes = R.drawable.ad),
            Country(name = "Angola", currency = "AOA", flagRes = R.drawable.ao),
            Country(name = "Antigua and Barbuda", currency = "XCD", flagRes = R.drawable.ag),
            Country(name = "Argentina", currency = "ARS", flagRes = R.drawable.ar),
            Country(name = "Armenia", currency = "AMD", flagRes = R.drawable.am),
            Country(name = "Australia", currency = "AUD", flagRes = R.drawable.au),
            Country(name = "Austria", currency = "EUR", flagRes = R.drawable.at),
            Country(name = "Azerbaijan", currency = "AZN", flagRes = R.drawable.az),
            Country(name = "Bahamas", currency = "BSD", flagRes = R.drawable.bahamas),
            Country(name = "Bahrain", currency = "BHD", flagRes = R.drawable.bh),
            Country(name = "Bangladesh", currency = "BDT", flagRes = R.drawable.bd),
            Country(name = "Barbados", currency = "BBD", flagRes = R.drawable.bb),
            Country(name = "Belarus", currency = "BYN", flagRes = R.drawable.by),
            Country(name = "Belgium", currency = "EUR", flagRes = R.drawable.be),
            Country(name = "Belize", currency = "BZD", flagRes = R.drawable.bz),
            Country(name = "Benin", currency = "XOF", flagRes = R.drawable.bj),
            Country(name = "Bhutan", currency = "BTN", flagRes = R.drawable.bt),
            Country(name = "Bolivia", currency = "BOB", flagRes = R.drawable.bo),
            Country(name = "Bosnia and Herzegovina", currency = "BAM", flagRes = R.drawable.ba),
            Country(name = "Botswana", currency = "BWP", flagRes = R.drawable.bw),
            Country(name = "Brazil", currency = "BRL", flagRes = R.drawable.br),
            Country(name = "Brunei", currency = "BND", flagRes = R.drawable.bn),
            Country(name = "Bulgaria", currency = "BGN", flagRes = R.drawable.bg),
            Country(name = "Burkina Faso", currency = "XOF", flagRes = R.drawable.bf),
            Country(name = "Burundi", currency = "BIF", flagRes = R.drawable.bi),
            Country(name = "Cabo Verde", currency = "CVE", flagRes = R.drawable.cv),
            Country(name = "Cambodia", currency = "KHR", flagRes = R.drawable.kh),
            Country(name = "Cameroon", currency = "XAF", flagRes = R.drawable.cm),
            Country(name = "Canada", currency = "CAD", flagRes =   R.drawable.ca),
            Country(name = "Central African Republic", currency = "XAF", flagRes = R.drawable.cf),
            Country(name = "Chad", currency = "XAF", flagRes = R.drawable.td),
            Country(name = "Chile", currency = "CLP", flagRes = R.drawable.cl),
            Country(name = "China", currency = "CNY", flagRes = R.drawable.cn),
            Country(name = "Colombia", currency = "COP", flagRes = R.drawable.co),
            Country(name = "Comoros", currency = "KMF", flagRes = R.drawable.km),
            Country(name = "Congo, Democratic Republic of the", currency = "CDF", flagRes = R.drawable.cd),
            Country(name = "Congo, Republic of the", currency = "XAF", flagRes = R.drawable.cg),
            Country(name = "Costa Rica", currency = "CRC", flagRes = R.drawable.cr),
            Country(name = "Cote d'Ivoire", currency = "XOF", flagRes = R.drawable.ci),
            Country(name = "Croatia", currency = "EUR", flagRes = R.drawable.hr),
            Country(name = "Cuba", currency = "CUP", flagRes = R.drawable.cu),
            Country(name = "Cyprus", currency = "EUR", flagRes = R.drawable.cy),
            Country(name = "Czechia", currency = "CZK", flagRes = R.drawable.cz),
            Country(name = "Denmark", currency = "DKK", flagRes = R.drawable.dk),
            Country(name = "Djibouti", currency = "DJF", flagRes = R.drawable.dj),
            Country(name = "Dominica", currency = "XCD", flagRes = R.drawable.ic_flag),
            Country(name = "Dominican Republic", currency = "DOP", flagRes = R.drawable.dominicana),
            Country(name = "Ecuador", currency = "USD", flagRes = R.drawable.ec),
            Country(name = "Egypt", currency = "EGP", flagRes = R.drawable.eg),
            Country(name = "El Salvador", currency = "USD", flagRes = R.drawable.sv),
            Country(name = "Equatorial Guinea", currency = "XAF", flagRes = R.drawable.gq),
            Country(name = "Eritrea", currency = "ERN", flagRes = R.drawable.er),
            Country(name = "Estonia", currency = "EUR", flagRes = R.drawable.ee),
            Country(name = "Eswatini", currency = "SZL", flagRes = R.drawable.sz),
            Country(name = "Ethiopia", currency = "ETB", flagRes = R.drawable.et),
            Country(name = "Fiji", currency = "FJD", flagRes = R.drawable.fj),
            Country(name = "Finland", currency = "EUR", flagRes = R.drawable.fi),
            Country(name = "France", currency = "EUR", flagRes = R.drawable.fr),
            Country(name = "Gabon", currency = "XAF", flagRes = R.drawable.ga),
            Country(name = "Gambia", currency = "GMD", flagRes = R.drawable.gm),
            Country(name = "Georgia", currency = "GEL", flagRes = R.drawable.ic_flag),
            Country(name = "Germany", currency = "EUR", flagRes = R.drawable.de),
            Country(name = "Ghana", currency = "GHS", flagRes = R.drawable.gh),
            Country(name = "Greece", currency = "EUR", flagRes = R.drawable.gr),
            Country(name = "Grenada", currency = "XCD", flagRes = R.drawable.gd),
            Country(name = "Guatemala", currency = "GTQ", flagRes = R.drawable.gt),
            Country(name = "Guinea", currency = "GNF", flagRes = R.drawable.gn),
            Country(name = "Guinea-Bissau", currency = "XOF", flagRes = R.drawable.gw),
            Country(name = "Guyana", currency = "GYD", flagRes = R.drawable.gy),
            Country(name = "Haiti", currency = "HTG", flagRes =  R.drawable.ht),
            Country(name = "Honduras", currency = "HNL", flagRes = R.drawable.hn),
            Country(name = "Hungary", currency = "HUF", flagRes = R.drawable.hu),
            Country(name = "Iceland", currency = "ISK", flagRes = R.drawable.`is`),
            Country(name = "India", currency = "INR", flagRes = R.drawable.`in`),
            Country(name = "Indonesia", currency = "IDR", flagRes = R.drawable.id),
            Country(name = "Iran", currency = "IRR", flagRes = R.drawable.ir),
            Country(name = "Iraq", currency = "IQD", flagRes = R.drawable.iq),
            Country(name = "Ireland", currency = "EUR", flagRes = R.drawable.ie),
            Country(name = "Israel", currency = "ILS", flagRes = R.drawable.il),
            Country(name = "Italy", currency = "EUR", flagRes = R.drawable.it),
            Country(name = "Jamaica", currency = "JMD", flagRes = R.drawable.jm),
            Country(name = "Japan", currency = "JPY", flagRes = R.drawable.jp),
            Country(name = "Jordan", currency = "JOD", flagRes = R.drawable.jo),
            Country(name = "Kazakhstan", currency = "KZT", flagRes = R.drawable.kz),
            Country(name = "Kenya", currency = "KES", flagRes = R.drawable.ke),
            Country(name = "Kiribati", currency = "AUD", flagRes = R.drawable.ki),
            Country(name = "Kuwait", currency = "KWD", flagRes = R.drawable.kw),
            Country(name = "Kyrgyzstan", currency = "KGS", flagRes = R.drawable.kg),
            Country(name = "Laos", currency = "LAK", flagRes = R.drawable.la),
            Country(name = "Latvia", currency = "EUR", flagRes = R.drawable.lv),
            Country(name = "Lebanon", currency = "LBP", flagRes = R.drawable.lb),
            Country(name = "Lesotho", currency = "LSL", flagRes = R.drawable.ls),
            Country(name = "Liberia", currency = "LRD", flagRes = R.drawable.lr),
            Country(name = "Libya", currency = "LYD", flagRes = R.drawable.ly),
            Country(name = "Liechtenstein", currency = "CHF", flagRes = R.drawable.li),
            Country(name = "Lithuania", currency = "EUR", flagRes = R.drawable.lt),
            Country(name = "Luxembourg", currency = "EUR", flagRes = R.drawable.lu),
            Country(name = "Madagascar", currency = "MGA", flagRes = R.drawable.mg),
            Country(name = "Malawi", currency = "MWK", flagRes = R.drawable.mw),
            Country(name = "Malaysia", currency = "MYR", flagRes = R.drawable.my),
            Country(name = "Maldives", currency = "MVR", flagRes = R.drawable.mv),
            Country(name = "Mali", currency = "XOF", flagRes = R.drawable.ml),
            Country(name = "Malta", currency = "EUR", flagRes = R.drawable.mt),
            Country(name = "Marshall Islands", currency = "USD", flagRes = R.drawable.mh),
            Country(name = "Mauritania", currency = "MRU", flagRes = R.drawable.mr),
            Country(name = "Mauritius", currency = "MUR", flagRes = R.drawable.mu),
            Country(name = "Mexico", currency = "MXN", flagRes = R.drawable.mx),
            Country(name = "Micronesia", currency = "USD", flagRes = R.drawable.fm),
            Country(name = "Moldova", currency = "MDL", flagRes = R.drawable.md),
            Country(name = "Monaco", currency = "EUR", flagRes = R.drawable.mc),
            Country(name = "Mongolia", currency = "MNT", flagRes = R.drawable.mn),
            Country(name = "Montenegro", currency = "EUR", flagRes = R.drawable.me),
            Country(name = "Morocco", currency = "MAD", flagRes = R.drawable.ma),
            Country(name = "Mozambique", currency = "MZN", flagRes = R.drawable.mz),
            Country(name = "Myanmar", currency = "MMK", flagRes = R.drawable.mm),
            Country(name = "Namibia", currency = "NAD", flagRes = R.drawable.na),
            Country(name = "Nauru", currency = "AUD", flagRes = R.drawable.nr),
            Country(name = "Nepal", currency = "NPR", flagRes =   R.drawable.np),
            Country(name = "Netherlands", currency = "EUR", flagRes = R.drawable.nl),
            Country(name = "New Zealand", currency = "NZD", flagRes = R.drawable.nz),
            Country(name = "Nicaragua", currency = "NIO", flagRes = R.drawable.ni),
            Country(name = "Niger", currency = "XOF", flagRes = R.drawable.ne),
            Country(name = "Nigeria", currency = "NGN", flagRes = R.drawable.ng),
            Country(name = "North Korea", currency = "KPW", flagRes = R.drawable.kp),
            Country(name = "North Macedonia", currency = "MKD", flagRes = R.drawable.mk),
            Country(name = "Norway", currency = "NOK", flagRes = R.drawable.no),
            Country(name = "Oman", currency = "OMR", flagRes = R.drawable.om),
            Country(name = "Pakistan", currency = "PKR", flagRes = R.drawable.pk),
            Country(name = "Palau", currency = "USD", flagRes = R.drawable.pw),
            Country(name = "Panama", currency = "PAB", flagRes = R.drawable.pa),
            Country(name = "Papua New Guinea", currency = "PGK", flagRes = R.drawable.pg),
            Country(name = "Paraguay", currency = "PYG", flagRes = R.drawable.py),
            Country(name = "Peru", currency = "PEN", flagRes = R.drawable.pe),
            Country(name = "Philippines", currency = "PHP", flagRes = R.drawable.ph),
            Country(name = "Poland", currency = "PLN", flagRes = R.drawable.pl),
            Country(name = "Portugal", currency = "EUR", flagRes = R.drawable.pt),
            Country(name = "Qatar", currency = "QAR", flagRes = R.drawable.qa),
            Country(name = "Romania", currency = "RON", flagRes = R.drawable.ro),
            Country(name = "Russia", currency = "RUB", flagRes = R.drawable.ru),
            Country(name = "Rwanda", currency = "RWF", flagRes = R.drawable.rw),
            Country(name = "Saint Kitts and Nevis", currency = "XCD", flagRes = R.drawable.kn),
            Country(name = "Saint Lucia", currency = "XCD", flagRes = R.drawable.lc),
            Country(name = "Saint Vincent and the Grenadines", currency = "XCD", flagRes = R.drawable.vc),
            Country(name = "Samoa", currency = "WST", flagRes = R.drawable.ws),
            Country(name = "San Marino", currency = "EUR", flagRes = R.drawable.sm),
            Country(name = "Sao Tome and Principe", currency = "STN", flagRes = R.drawable.st),
            Country(name = "Saudi Arabia", currency = "SAR", flagRes = R.drawable.sa),
            Country(name = "Senegal", currency = "XOF", flagRes = R.drawable.sn),
            Country(name = "Serbia", currency = "RSD", flagRes = R.drawable.rs),
            Country(name = "Seychelles", currency = "SCR", flagRes = R.drawable.sc),
            Country(name = "Sierra Leone", currency = "SLL", flagRes = R.drawable.sl),
            Country(name = "Singapore", currency = "SGD", flagRes = R.drawable.sg),
            Country(name = "Slovakia", currency = "EUR", flagRes = R.drawable.sk),
            Country(name = "Slovenia", currency = "EUR", flagRes = R.drawable.si),
            Country(name = "Solomon Islands", currency = "SBD", flagRes = R.drawable.sb),
            Country(name = "Somalia", currency = "SOS", flagRes = R.drawable.so),
            Country(name = "South Africa", currency = "ZAR", flagRes = R.drawable.za),
            Country(name = "South Korea", currency = "KRW", flagRes = R.drawable.kr),
            Country(name = "South Sudan", currency = "SSP", flagRes = R.drawable.ss),
            Country(name = "Spain", currency = "EUR", flagRes = R.drawable.es),
            Country(name = "Sri Lanka", currency = "LKR", flagRes = R.drawable.lk),
            Country(name = "Sudan", currency = "SDG", flagRes = R.drawable.sd),
            Country(name = "Suriname", currency = "SRD", flagRes = R.drawable.sr),
            Country(name = "Sweden", currency = "SEK", flagRes = R.drawable.se),
            Country(name = "Switzerland", currency = "CHF", flagRes = R.drawable.ch),
            Country(name = "Syria", currency = "SYP", flagRes = R.drawable.sy),
            Country(name = "Taiwan", currency = "TWD", flagRes = R.drawable.tw),
            Country(name = "Tajikistan", currency = "TJS", flagRes = R.drawable.tj),
            Country(name = "Tanzania", currency = "TZS", flagRes = R.drawable.tz),
            Country(name = "Thailand", currency = "THB", flagRes = R.drawable.th),
            Country(name = "Timor-Leste", currency = "USD", flagRes = R.drawable.tl),
            Country(name = "Togo", currency = "XOF", flagRes = R.drawable.tg),
            Country(name = "Tonga", currency = "TOP", flagRes = R.drawable.to),
            Country(name = "Trinidad and Tobago", currency = "TTD", flagRes = R.drawable.tt),
            Country(name = "Tunisia", currency = "TND", flagRes = R.drawable.tn),
            Country(name = "Turkey", currency = "TRY", flagRes = R.drawable.tr),
            Country(name = "Turkmenistan", currency = "TMT", flagRes = R.drawable.tm),
            Country(name = "Tuvalu", currency = "AUD", flagRes = R.drawable.tv),
            Country(name = "Uganda", currency = "UGX", flagRes = R.drawable.ug),
            Country(name = "Ukraine", currency = "UAH", flagRes = R.drawable.ua),
            Country(name = "United Arab Emirates", currency = "AED", flagRes = R.drawable.ae),
            Country(name = "United Kingdom", currency = "GBP", flagRes = R.drawable.gb),
            Country(name = "United States of America", currency = "USD", flagRes = R.drawable.us),
            Country(name = "Uruguay", currency = "UYU", flagRes = R.drawable.uy),
            Country(name = "Uzbekistan", currency = "UZS", flagRes = R.drawable.uz),
            Country(name = "Vanuatu", currency = "VUV", flagRes = R.drawable.vu),
            Country(name = "Vatican City", currency = "EUR", flagRes = R.drawable.va),
            Country(name = "Venezuela", currency = "VES", flagRes = R.drawable.ve),
            Country(name = "Vietnam", currency = "VND", flagRes = R.drawable.vn),
            Country(name = "Yemen", currency = "YER", flagRes = R.drawable.ye),
            Country(name = "Zambia", currency = "ZMW", flagRes = R.drawable.zm),
            Country(name = "Zimbabwe", currency = "ZWL", flagRes = R.drawable.zw)
        )
    }

    fun getEuropeanCities(countryIdMap: Map<String, Int>): List<City> {
        return listOf(
            City(name = "Paris", countryId = countryIdMap["France"]!!),
            City(name = "Rome", countryId = countryIdMap["Italy"]!!),
            City(name = "Madrid", countryId = countryIdMap["Spain"]!!),
            City(name = "Barcelona", countryId = countryIdMap["Spain"]!!),
            City(name = "Berlin", countryId = countryIdMap["Germany"]!!),
            City(name = "Munich", countryId = countryIdMap["Germany"]!!),
            City(name = "Amsterdam", countryId = countryIdMap["Netherlands"]!!),
            City(name = "Brussels", countryId = countryIdMap["Belgium"]!!),
            City(name = "Vienna", countryId = countryIdMap["Austria"]!!),
            City(name = "Prague", countryId = countryIdMap["Czechia"]!!),
            City(name = "Budapest", countryId = countryIdMap["Hungary"]!!),
            City(name = "Lisbon", countryId = countryIdMap["Portugal"]!!),
            City(name = "Athens", countryId = countryIdMap["Greece"]!!),
            City(name = "Copenhagen", countryId = countryIdMap["Denmark"]!!),
            City(name = "Stockholm", countryId = countryIdMap["Sweden"]!!),
            City(name = "Oslo", countryId = countryIdMap["Norway"]!!),
            City(name = "Helsinki", countryId = countryIdMap["Finland"]!!),
            City(name = "Dublin", countryId = countryIdMap["Ireland"]!!),
            City(name = "Zurich", countryId = countryIdMap["Switzerland"]!!),
            City(name = "Venice", countryId = countryIdMap["Italy"]!!)
        )
    }


    fun getExpenseTypes(): List<ExpenseType> {
        return listOf(
            ExpenseType(name = "Accommodation", logo = "ic_accommodation"),
            ExpenseType(name = "Airline Tickets", logo = "ic_airline_tickets"),
            ExpenseType(name = "Food", logo = "ic_food"),
            ExpenseType(name = "Transport", logo = "ic_transport"),
            ExpenseType(name = "Leisure", logo = "ic_leisure"),
            ExpenseType(name = "Insurance", logo = "ic_insurance"),
            ExpenseType(name = "Health", logo = "ic_health"),
            ExpenseType(name = "Parking", logo = "ic_parking"),
            ExpenseType(name = "Drinks", logo = "ic_drinks"),
            ExpenseType(name = "Others", logo = "ic_others"),
            ExpenseType(name = "Souvenirs", logo = "ic_souvenirs"),
            ExpenseType(name = "Tolls", logo = "ic_tolls")
        )
    }

    fun getProviders(): List<Provider> {
        return listOf(
            Provider(name = "Ryanair", logo = "logo_ryanair"),
            Provider(name = "Lufthansa", logo = "logo_lufthansa"),
            Provider(name = "KLM", logo = "logo_klm"),
            Provider(name = "Air France", logo = "logo_airfrance"),
            Provider(name = "British Airways", logo = "logo_britishairways"),
            Provider(name = "Iberia", logo = "logo_iberia"),
            Provider(name = "Aer Lingus", logo = "logo_aerlingus"),
            Provider(name = "easyJet", logo = "logo_easyjet"),
            Provider(name = "Turkish Airlines", logo = "logo_turkishairlines"),
            Provider(name = "Norwegian", logo = "logo_norwegian"),
            Provider(name = "AirEuropa", logo = "logo_aireuropa"),
            Provider(name = "Conviasa", logo = "logo_conviasa"),
            Provider(name = "Copa Airlines", logo = "logo_copaairlines"),
            Provider(name = "American Airlines", logo = "logo_americanairlines"),
            Provider(name = "booking.com", logo = "logo_bookingcom"),
            Provider(name = "loveholidays.com", logo = "logo_loveholidayscom"),
            Provider(name = "Hertz", logo = "logo_hertz"),
            Provider(name = "Avis", logo = "logo_avis"),
            Provider(name = "Europcar", logo = "logo_europcar"),
            Provider(name = "Sixt", logo = "logo_sixt"),
            Provider(name = "Enterprise", logo = "logo_enterprise"),
            Provider(name = "Goldcar", logo = "logo_goldcar"),
            Provider(name = "Dublin Airport", logo = "logo_dublinairport"),
            Provider(name = "Shannon Airport", logo = "logo_shannonairport"),
            Provider(name = "Cork Airport", logo = "logo_corkairport"),
            Provider(name = "Bus Eireann", logo = "logo_buseireann"),
            Provider(name = "Go-Ahead Ireland", logo = "logo_goaheadireland"),
            Provider(name = "Dublin Bus", logo = "logo_dublinbus"),
            Provider(name = "VHI Healthcare", logo = "logo_vhihealthcare"),
            Provider(name = "Laya Healthcare", logo = "logo_layahealthcare"),
            Provider(name = "Irish Life Health", logo = "logo_irishlifehealth"),
            Provider(name = "Aviva", logo = "logo_aviva"),
            Provider(name = "AXA", logo = "logo_axa")
        )
    }
}