package io.github.jlrods.mytripsmanager.ui.utils

import io.github.jlrods.mytripsmanager.R


//TODO: To be deleted as map is not required any longer.
fun getFlagRes(code: String, function: () -> Int): Int {
    return when (code.lowercase()) {
        "ad" -> R.drawable.ad
        "ae" -> R.drawable.ae
        "af" -> R.drawable.afganistan
        "ag" -> R.drawable.ag
        "al" -> R.drawable.al
        "am" -> R.drawable.am
        "ao" -> R.drawable.ao
        "ar" -> R.drawable.ar
        "at" -> R.drawable.at
        "au" -> R.drawable.au
        "az" -> R.drawable.az
        "ba" -> R.drawable.ba
        "bb" -> R.drawable.bb
        "bd" -> R.drawable.bd
        "be" -> R.drawable.be
        "bf" -> R.drawable.bf
        "bg" -> R.drawable.bg
        "bh" -> R.drawable.bh
        "bi" -> R.drawable.bi
        "bj" -> R.drawable.bj
        "bn" -> R.drawable.bn
        "bo" -> R.drawable.bo
        "br" -> R.drawable.br
        "bs" -> R.drawable.bahamas
        "bt" -> R.drawable.bt
        "bw" -> R.drawable.bw
        "by" -> R.drawable.by
        "bz" -> R.drawable.bz
        "ca" -> R.drawable.ca
        "cd" -> R.drawable.cd
        "cf" -> R.drawable.cf
        "cg" -> R.drawable.cg
        "ch" -> R.drawable.ch
        "ci" -> R.drawable.ci
        "cl" -> R.drawable.cl
        "cm" -> R.drawable.cm
        "cn" -> R.drawable.cn
        "co" -> R.drawable.co
        "cr" -> R.drawable.cr
        "cu" -> R.drawable.cu
        "cv" -> R.drawable.cv
        "cy" -> R.drawable.cy
        "cz" -> R.drawable.cz
        "de" -> R.drawable.de
        "dj" -> R.drawable.dj
        "dk" -> R.drawable.dk
        "do" -> R.drawable.dominicana
        "dz" -> R.drawable.dz
        "ec" -> R.drawable.ec
        "ee" -> R.drawable.ee
        "eg" -> R.drawable.eg
        "er" -> R.drawable.er
        "es" -> R.drawable.es
        "et" -> R.drawable.et
        "fi" -> R.drawable.fi
        "fj" -> R.drawable.fj
        "fm" -> R.drawable.fm
        "fr" -> R.drawable.fr
        "ga" -> R.drawable.ga
        "gb" -> R.drawable.gb
        "gb_eng" -> R.drawable.gb_eng
        "gb_sct" -> R.drawable.gb_sct
        "gb_wls" -> R.drawable.gb_wls
        "gd" -> R.drawable.gd
        "gh" -> R.drawable.gh
        "gm" -> R.drawable.gm
        "gn" -> R.drawable.gn
        "gq" -> R.drawable.gq
        "gr" -> R.drawable.gr
        "gt" -> R.drawable.gt
        "gw" -> R.drawable.gw
        "gy" -> R.drawable.gy
        "hn" -> R.drawable.hn
        "hr" -> R.drawable.hr
        "ht" -> R.drawable.ht
        "hu" -> R.drawable.hu
        "id" -> R.drawable.id
        "ie" -> R.drawable.ie
        "il" -> R.drawable.il
        "in" -> R.drawable.`in`
        "iq" -> R.drawable.iq
        "ir" -> R.drawable.ir
        "is" -> R.drawable.`is`
        "it" -> R.drawable.it
        "jm" -> R.drawable.jm
        "jo" -> R.drawable.jo
        "jp" -> R.drawable.jp
        "ke" -> R.drawable.ke
        "kg" -> R.drawable.kg
        "kh" -> R.drawable.kh
        "ki" -> R.drawable.ki
        "km" -> R.drawable.km
        "kn" -> R.drawable.kn
        "kp" -> R.drawable.kp
        "kr" -> R.drawable.kr
        "kw" -> R.drawable.kw
        "kz" -> R.drawable.kz
        "la" -> R.drawable.la
        "lb" -> R.drawable.lb
        "lc" -> R.drawable.lc
        "li" -> R.drawable.li
        "lk" -> R.drawable.lk
        "lr" -> R.drawable.lr
        "ls" -> R.drawable.ls
        "lt" -> R.drawable.lt
        "lu" -> R.drawable.lu
        "lv" -> R.drawable.lv
        "ly" -> R.drawable.ly
        "ma" -> R.drawable.ma
        "mc" -> R.drawable.mc
        "md" -> R.drawable.md
        "me" -> R.drawable.me
        "mg" -> R.drawable.mg
        "mh" -> R.drawable.mh
        "mk" -> R.drawable.mk
        "ml" -> R.drawable.ml
        "mm" -> R.drawable.mm
        "mn" -> R.drawable.mn
        "mr" -> R.drawable.mr
        "mt" -> R.drawable.mt
        "mu" -> R.drawable.mu
        "mv" -> R.drawable.mv
        "mw" -> R.drawable.mw
        "mx" -> R.drawable.mx
        "my" -> R.drawable.my
        "mz" -> R.drawable.mz
        "na" -> R.drawable.na
        "ne" -> R.drawable.ne
        "ng" -> R.drawable.ng
        "ni" -> R.drawable.ni
        "nl" -> R.drawable.nl
        "no" -> R.drawable.no
        "np" -> R.drawable.np
        "nr" -> R.drawable.nr
        "nz" -> R.drawable.nz
        "om" -> R.drawable.om
        "pa" -> R.drawable.pa
        "pe" -> R.drawable.pe
        "pg" -> R.drawable.pg
        "ph" -> R.drawable.ph
        "pk" -> R.drawable.pk
        "pl" -> R.drawable.pl
        "pt" -> R.drawable.pt
        "pw" -> R.drawable.pw
        "py" -> R.drawable.py
        "qa" -> R.drawable.qa
        "ro" -> R.drawable.ro
        "rs" -> R.drawable.rs
        "ru" -> R.drawable.ru
        "rw" -> R.drawable.rw
        "sa" -> R.drawable.sa
        "sb" -> R.drawable.sb
        "sc" -> R.drawable.sc
        "sd" -> R.drawable.sd
        "se" -> R.drawable.se
        "sg" -> R.drawable.sg
        "si" -> R.drawable.si
        "sk" -> R.drawable.sk
        "sl" -> R.drawable.sl
        "sm" -> R.drawable.sm
        "sn" -> R.drawable.sn
        "so" -> R.drawable.so
        "sr" -> R.drawable.sr
        "ss" -> R.drawable.ss
        "st" -> R.drawable.st
        "sv" -> R.drawable.sv
        "sy" -> R.drawable.sy
        "sz" -> R.drawable.sz
        "td" -> R.drawable.td
        "tg" -> R.drawable.tg
        "th" -> R.drawable.th
        "tj" -> R.drawable.tj
        "tl" -> R.drawable.tl
        "tm" -> R.drawable.tm
        "tn" -> R.drawable.tn
        "to" -> R.drawable.to
        "tr" -> R.drawable.tr
        "tt" -> R.drawable.tt
        "tv" -> R.drawable.tv
        "tw" -> R.drawable.tw
        "tz" -> R.drawable.tz
        "ua" -> R.drawable.ua
        "ug" -> R.drawable.ug
        "us" -> R.drawable.us
        "uy" -> R.drawable.uy
        "uz" -> R.drawable.uz
        "va" -> R.drawable.va
        "vc" -> R.drawable.vc
        "ve" -> R.drawable.ve
        "vn" -> R.drawable.vn
        "vu" -> R.drawable.vu
        "ws" -> R.drawable.ws
        "ye" -> R.drawable.ye
        "za" -> R.drawable.za
        "zm" -> R.drawable.zm
        "zw" -> R.drawable.zw
        else -> R.drawable.ic_flag
    }
}
